services:
  - name: ipl-auction-frontend
    type: web
    env: node
    branch: main
    buildCommand: cd 1.2/ipl-auction-game/frontend && yarn install --production=false && yarn build
    startCommand: cd 1.2/ipl-auction-game/frontend && yarn preview
    envVars:
      - key: NODE_ENV
        value: production
    publishPath: 1.2/ipl-auction-game/frontend/dist

  - name: ipl-auction-backend
    type: web
    env: node
    branch: main
    buildCommand: cd 1.2/ipl-auction-game/backend && yarn install
    startCommand: cd 1.2/ipl-auction-game/backend && node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
